import type { CapacitorConfig } from '@capacitor/cli';

// Capacitor packages this app for Android/iOS. It ships the static shell in
// `dist/capacitor/` (generated by `scripts/build-capacitor.mjs` during
// `npm run build`) and points the WebView at the published Lovable URL so
// the SSR/PWA runtime stays identical to the web app.
const config: CapacitorConfig = {
  appId: 'app.bookary.reader',
  appName: 'Bookary',
  webDir: 'dist/capacitor',
  android: {
    allowMixedContent: false,
  },
  server: {
    androidScheme: 'https',
    // The app is an SSR TanStack Start site — there is no fully static build
    // we can ship offline. The Android WebView loads the live published site;
    // the PWA service worker then caches assets and offline navigations.
    url: 'https://bookary-boost-engine.lovable.app',
    cleartext: false,
  },
  plugins: {
    SplashScreen: {
      launchShowDuration: 1200,
      backgroundColor: '#0b0a1a',
      showSpinner: false,
      androidSplashResourceName: 'splash',
    },
  },
};

export default config;
