/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WritersRouteImport } from './routes/writers'
import { Route as TrackingRouteImport } from './routes/tracking'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SearchRouteImport } from './routes/search'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as LovedRouteImport } from './routes/loved'
import { Route as LanguagesRouteImport } from './routes/languages'
import { Route as GenresRouteImport } from './routes/genres'
import { Route as DiaryRouteImport } from './routes/diary'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WritersIndexRouteImport } from './routes/writers.index'
import { Route as LanguagesIndexRouteImport } from './routes/languages.index'
import { Route as GenresIndexRouteImport } from './routes/genres.index'
import { Route as WritersSlugRouteImport } from './routes/writers.$slug'
import { Route as UIdRouteImport } from './routes/u.$id'
import { Route as LibrariesSlugRouteImport } from './routes/libraries.$slug'
import { Route as LanguagesSlugRouteImport } from './routes/languages.$slug'
import { Route as GenresSlugRouteImport } from './routes/genres.$slug'
import { Route as BooksIdRouteImport } from './routes/books.$id'

const WritersRoute = WritersRouteImport.update({
  id: '/writers',
  path: '/writers',
  getParentRoute: () => rootRouteImport,
} as any)
const TrackingRoute = TrackingRouteImport.update({
  id: '/tracking',
  path: '/tracking',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const LovedRoute = LovedRouteImport.update({
  id: '/loved',
  path: '/loved',
  getParentRoute: () => rootRouteImport,
} as any)
const LanguagesRoute = LanguagesRouteImport.update({
  id: '/languages',
  path: '/languages',
  getParentRoute: () => rootRouteImport,
} as any)
const GenresRoute = GenresRouteImport.update({
  id: '/genres',
  path: '/genres',
  getParentRoute: () => rootRouteImport,
} as any)
const DiaryRoute = DiaryRouteImport.update({
  id: '/diary',
  path: '/diary',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WritersIndexRoute = WritersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => WritersRoute,
} as any)
const LanguagesIndexRoute = LanguagesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LanguagesRoute,
} as any)
const GenresIndexRoute = GenresIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => GenresRoute,
} as any)
const WritersSlugRoute = WritersSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => WritersRoute,
} as any)
const UIdRoute = UIdRouteImport.update({
  id: '/u/$id',
  path: '/u/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const LibrariesSlugRoute = LibrariesSlugRouteImport.update({
  id: '/libraries/$slug',
  path: '/libraries/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const LanguagesSlugRoute = LanguagesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => LanguagesRoute,
} as any)
const GenresSlugRoute = GenresSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => GenresRoute,
} as any)
const BooksIdRoute = BooksIdRouteImport.update({
  id: '/books/$id',
  path: '/books/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/diary': typeof DiaryRoute
  '/genres': typeof GenresRouteWithChildren
  '/languages': typeof LanguagesRouteWithChildren
  '/loved': typeof LovedRoute
  '/profile': typeof ProfileRoute
  '/search': typeof SearchRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tracking': typeof TrackingRoute
  '/writers': typeof WritersRouteWithChildren
  '/books/$id': typeof BooksIdRoute
  '/genres/$slug': typeof GenresSlugRoute
  '/languages/$slug': typeof LanguagesSlugRoute
  '/libraries/$slug': typeof LibrariesSlugRoute
  '/u/$id': typeof UIdRoute
  '/writers/$slug': typeof WritersSlugRoute
  '/genres/': typeof GenresIndexRoute
  '/languages/': typeof LanguagesIndexRoute
  '/writers/': typeof WritersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/diary': typeof DiaryRoute
  '/loved': typeof LovedRoute
  '/profile': typeof ProfileRoute
  '/search': typeof SearchRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tracking': typeof TrackingRoute
  '/books/$id': typeof BooksIdRoute
  '/genres/$slug': typeof GenresSlugRoute
  '/languages/$slug': typeof LanguagesSlugRoute
  '/libraries/$slug': typeof LibrariesSlugRoute
  '/u/$id': typeof UIdRoute
  '/writers/$slug': typeof WritersSlugRoute
  '/genres': typeof GenresIndexRoute
  '/languages': typeof LanguagesIndexRoute
  '/writers': typeof WritersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/diary': typeof DiaryRoute
  '/genres': typeof GenresRouteWithChildren
  '/languages': typeof LanguagesRouteWithChildren
  '/loved': typeof LovedRoute
  '/profile': typeof ProfileRoute
  '/search': typeof SearchRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tracking': typeof TrackingRoute
  '/writers': typeof WritersRouteWithChildren
  '/books/$id': typeof BooksIdRoute
  '/genres/$slug': typeof GenresSlugRoute
  '/languages/$slug': typeof LanguagesSlugRoute
  '/libraries/$slug': typeof LibrariesSlugRoute
  '/u/$id': typeof UIdRoute
  '/writers/$slug': typeof WritersSlugRoute
  '/genres/': typeof GenresIndexRoute
  '/languages/': typeof LanguagesIndexRoute
  '/writers/': typeof WritersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/diary'
    | '/genres'
    | '/languages'
    | '/loved'
    | '/profile'
    | '/search'
    | '/sitemap.xml'
    | '/tracking'
    | '/writers'
    | '/books/$id'
    | '/genres/$slug'
    | '/languages/$slug'
    | '/libraries/$slug'
    | '/u/$id'
    | '/writers/$slug'
    | '/genres/'
    | '/languages/'
    | '/writers/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/auth'
    | '/diary'
    | '/loved'
    | '/profile'
    | '/search'
    | '/sitemap.xml'
    | '/tracking'
    | '/books/$id'
    | '/genres/$slug'
    | '/languages/$slug'
    | '/libraries/$slug'
    | '/u/$id'
    | '/writers/$slug'
    | '/genres'
    | '/languages'
    | '/writers'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/diary'
    | '/genres'
    | '/languages'
    | '/loved'
    | '/profile'
    | '/search'
    | '/sitemap.xml'
    | '/tracking'
    | '/writers'
    | '/books/$id'
    | '/genres/$slug'
    | '/languages/$slug'
    | '/libraries/$slug'
    | '/u/$id'
    | '/writers/$slug'
    | '/genres/'
    | '/languages/'
    | '/writers/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AuthRoute: typeof AuthRoute
  DiaryRoute: typeof DiaryRoute
  GenresRoute: typeof GenresRouteWithChildren
  LanguagesRoute: typeof LanguagesRouteWithChildren
  LovedRoute: typeof LovedRoute
  ProfileRoute: typeof ProfileRoute
  SearchRoute: typeof SearchRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TrackingRoute: typeof TrackingRoute
  WritersRoute: typeof WritersRouteWithChildren
  BooksIdRoute: typeof BooksIdRoute
  LibrariesSlugRoute: typeof LibrariesSlugRoute
  UIdRoute: typeof UIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/writers': {
      id: '/writers'
      path: '/writers'
      fullPath: '/writers'
      preLoaderRoute: typeof WritersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tracking': {
      id: '/tracking'
      path: '/tracking'
      fullPath: '/tracking'
      preLoaderRoute: typeof TrackingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/loved': {
      id: '/loved'
      path: '/loved'
      fullPath: '/loved'
      preLoaderRoute: typeof LovedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/languages': {
      id: '/languages'
      path: '/languages'
      fullPath: '/languages'
      preLoaderRoute: typeof LanguagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/genres': {
      id: '/genres'
      path: '/genres'
      fullPath: '/genres'
      preLoaderRoute: typeof GenresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diary': {
      id: '/diary'
      path: '/diary'
      fullPath: '/diary'
      preLoaderRoute: typeof DiaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/writers/': {
      id: '/writers/'
      path: '/'
      fullPath: '/writers/'
      preLoaderRoute: typeof WritersIndexRouteImport
      parentRoute: typeof WritersRoute
    }
    '/languages/': {
      id: '/languages/'
      path: '/'
      fullPath: '/languages/'
      preLoaderRoute: typeof LanguagesIndexRouteImport
      parentRoute: typeof LanguagesRoute
    }
    '/genres/': {
      id: '/genres/'
      path: '/'
      fullPath: '/genres/'
      preLoaderRoute: typeof GenresIndexRouteImport
      parentRoute: typeof GenresRoute
    }
    '/writers/$slug': {
      id: '/writers/$slug'
      path: '/$slug'
      fullPath: '/writers/$slug'
      preLoaderRoute: typeof WritersSlugRouteImport
      parentRoute: typeof WritersRoute
    }
    '/u/$id': {
      id: '/u/$id'
      path: '/u/$id'
      fullPath: '/u/$id'
      preLoaderRoute: typeof UIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/libraries/$slug': {
      id: '/libraries/$slug'
      path: '/libraries/$slug'
      fullPath: '/libraries/$slug'
      preLoaderRoute: typeof LibrariesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/languages/$slug': {
      id: '/languages/$slug'
      path: '/$slug'
      fullPath: '/languages/$slug'
      preLoaderRoute: typeof LanguagesSlugRouteImport
      parentRoute: typeof LanguagesRoute
    }
    '/genres/$slug': {
      id: '/genres/$slug'
      path: '/$slug'
      fullPath: '/genres/$slug'
      preLoaderRoute: typeof GenresSlugRouteImport
      parentRoute: typeof GenresRoute
    }
    '/books/$id': {
      id: '/books/$id'
      path: '/books/$id'
      fullPath: '/books/$id'
      preLoaderRoute: typeof BooksIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface GenresRouteChildren {
  GenresSlugRoute: typeof GenresSlugRoute
  GenresIndexRoute: typeof GenresIndexRoute
}

const GenresRouteChildren: GenresRouteChildren = {
  GenresSlugRoute: GenresSlugRoute,
  GenresIndexRoute: GenresIndexRoute,
}

const GenresRouteWithChildren =
  GenresRoute._addFileChildren(GenresRouteChildren)

interface LanguagesRouteChildren {
  LanguagesSlugRoute: typeof LanguagesSlugRoute
  LanguagesIndexRoute: typeof LanguagesIndexRoute
}

const LanguagesRouteChildren: LanguagesRouteChildren = {
  LanguagesSlugRoute: LanguagesSlugRoute,
  LanguagesIndexRoute: LanguagesIndexRoute,
}

const LanguagesRouteWithChildren = LanguagesRoute._addFileChildren(
  LanguagesRouteChildren,
)

interface WritersRouteChildren {
  WritersSlugRoute: typeof WritersSlugRoute
  WritersIndexRoute: typeof WritersIndexRoute
}

const WritersRouteChildren: WritersRouteChildren = {
  WritersSlugRoute: WritersSlugRoute,
  WritersIndexRoute: WritersIndexRoute,
}

const WritersRouteWithChildren =
  WritersRoute._addFileChildren(WritersRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AuthRoute: AuthRoute,
  DiaryRoute: DiaryRoute,
  GenresRoute: GenresRouteWithChildren,
  LanguagesRoute: LanguagesRouteWithChildren,
  LovedRoute: LovedRoute,
  ProfileRoute: ProfileRoute,
  SearchRoute: SearchRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TrackingRoute: TrackingRoute,
  WritersRoute: WritersRouteWithChildren,
  BooksIdRoute: BooksIdRoute,
  LibrariesSlugRoute: LibrariesSlugRoute,
  UIdRoute: UIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
