/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WritersRouteImport } from './routes/writers'
import { Route as SearchRouteImport } from './routes/search'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as LovedRouteImport } from './routes/loved'
import { Route as GenresRouteImport } from './routes/genres'
import { Route as DiaryRouteImport } from './routes/diary'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BooksIdRouteImport } from './routes/books.$id'

const WritersRoute = WritersRouteImport.update({
  id: '/writers',
  path: '/writers',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const LovedRoute = LovedRouteImport.update({
  id: '/loved',
  path: '/loved',
  getParentRoute: () => rootRouteImport,
} as any)
const GenresRoute = GenresRouteImport.update({
  id: '/genres',
  path: '/genres',
  getParentRoute: () => rootRouteImport,
} as any)
const DiaryRoute = DiaryRouteImport.update({
  id: '/diary',
  path: '/diary',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BooksIdRoute = BooksIdRouteImport.update({
  id: '/books/$id',
  path: '/books/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/diary': typeof DiaryRoute
  '/genres': typeof GenresRoute
  '/loved': typeof LovedRoute
  '/profile': typeof ProfileRoute
  '/search': typeof SearchRoute
  '/writers': typeof WritersRoute
  '/books/$id': typeof BooksIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/diary': typeof DiaryRoute
  '/genres': typeof GenresRoute
  '/loved': typeof LovedRoute
  '/profile': typeof ProfileRoute
  '/search': typeof SearchRoute
  '/writers': typeof WritersRoute
  '/books/$id': typeof BooksIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/diary': typeof DiaryRoute
  '/genres': typeof GenresRoute
  '/loved': typeof LovedRoute
  '/profile': typeof ProfileRoute
  '/search': typeof SearchRoute
  '/writers': typeof WritersRoute
  '/books/$id': typeof BooksIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/diary'
    | '/genres'
    | '/loved'
    | '/profile'
    | '/search'
    | '/writers'
    | '/books/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/diary'
    | '/genres'
    | '/loved'
    | '/profile'
    | '/search'
    | '/writers'
    | '/books/$id'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/diary'
    | '/genres'
    | '/loved'
    | '/profile'
    | '/search'
    | '/writers'
    | '/books/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  DiaryRoute: typeof DiaryRoute
  GenresRoute: typeof GenresRoute
  LovedRoute: typeof LovedRoute
  ProfileRoute: typeof ProfileRoute
  SearchRoute: typeof SearchRoute
  WritersRoute: typeof WritersRoute
  BooksIdRoute: typeof BooksIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/writers': {
      id: '/writers'
      path: '/writers'
      fullPath: '/writers'
      preLoaderRoute: typeof WritersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/loved': {
      id: '/loved'
      path: '/loved'
      fullPath: '/loved'
      preLoaderRoute: typeof LovedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/genres': {
      id: '/genres'
      path: '/genres'
      fullPath: '/genres'
      preLoaderRoute: typeof GenresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diary': {
      id: '/diary'
      path: '/diary'
      fullPath: '/diary'
      preLoaderRoute: typeof DiaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/books/$id': {
      id: '/books/$id'
      path: '/books/$id'
      fullPath: '/books/$id'
      preLoaderRoute: typeof BooksIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  DiaryRoute: DiaryRoute,
  GenresRoute: GenresRoute,
  LovedRoute: LovedRoute,
  ProfileRoute: ProfileRoute,
  SearchRoute: SearchRoute,
  WritersRoute: WritersRoute,
  BooksIdRoute: BooksIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
